[workspace]
resolver = "2"
members = ["apple-tracing-sub", "rslib", "uniffi-bindgen"]

[workspace.dependencies]
uniffi = "0.29.0"

[profile.release]
opt-level = "z"
lto = "thin"
panic = "abort"
strip = "symbols"
